# -*- coding: utf-8 -*-
"""TP4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wl7sm5jAtWwvEnSlBc0mNucgjK66_Nu7

# TRABAJO PRÁCTICO N° 4: GENERACIÓN DE VARIABLES ALEATORIAS
**Cátedra:** Simulación - UTN FRBA  
**Objetivo:** Procesamiento de datos de guardia hospitalaria, ajuste de FDP (IA y TA) y simulación por Transformada Inversa.
"""

# !pip install numpy fitter pandas matplotlib seaborn scipy

"""# 1. IMPORTACIÓN DE LIBRERÍAS"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from fitter import Fitter

# Configuración visual
sns.set_theme(style="whitegrid")
plt.rcParams['figure.figsize'] = (10, 5)
plt.rcParams['font.size'] = 10

"""#2. CARGA DE DATOS (GOOGLE COLAB)"""

archivo_csv = "../datos/ER Wait Time Dataset.csv"
ruta_drive = "/content/drive/MyDrive/TP4/Datos/ER Wait Time Dataset.csv"

if os.path.exists(archivo_csv):
    df_raw = pd.read_csv(archivo_csv)
    print(f"Cargado exitosamente desde archivo local: {archivo_csv}")
elif os.path.exists(ruta_drive):
    df_raw = pd.read_csv(ruta_drive)
    print(f"Cargado exitosamente desde Google Drive: {ruta_drive}")
else:
    try:
        from google.colab import drive
        drive.mount('/content/drive')
        df_raw = pd.read_csv(ruta_drive)
        print("Cargado tras montar Google Drive.")
    except Exception as e:
        raise FileNotFoundError(f"No se encontró el dataset. Colocalo en la misma carpeta que este script. Error: {e}")

print(f"Dimensiones del dataset: {df_raw.shape[0]} filas, {df_raw.shape[1]} columnas (Cumple requisito >= 3000).")

"""#3. PREPROCESAMIENTO Y DEFINICIÓN DE VARIABLES
1. Conversión a datetime
2. Variable TA: Tiempo de Atención con el Profesional Médico
3. Variable IA: Intervalo entre Arribos (orden cronológico obligatorio)
4. IA discriminado por hospital (un paciente llega a la guardia de un hospital específico)
5. IA global consolidado (para análisis conjunto de la red)
"""

df = df_raw.copy()

df['Visit Date'] = pd.to_datetime(df['Visit Date'])

df['TA_min'] = df['Time to Medical Professional (min)'].astype(float)

df = df.sort_values('Visit Date').reset_index(drop=True)

df['IA_min'] = df.groupby('Hospital ID')['Visit Date'].diff().dt.total_seconds() / 60.0

df['IA_global_min'] = df['Visit Date'].diff().dt.total_seconds() / 60.0

print("Registros por cada hospital:")
print(df['Hospital ID'].value_counts())

df_raw.columns.tolist()
df_raw.head()

"""#4. ANÁLISIS EXPLORATORIO DE DATOS (EDA)
GRAFICOS A UTILIZAR:
1. Gráficos de Análisis Exploratorio
2. Distribución IA
3. Boxplot IA
4. Distribución TA (Atención Médica)
5. Boxplot TA
"""

print("\n" + "="*80)
print(f"{'Hospital':<10} | {'Muestra':<7} | {'IA Prom (min)':<14} | {'IA Mediana':<12} | {'TA Prom (min)':<14} | {'TA Mediana':<12}")
print("="*80)
for hosp in sorted(df['Hospital ID'].unique()):
    sub = df[df['Hospital ID'] == hosp]
    ia_data = sub['IA_min'].dropna()
    ta_data = sub['TA_min'].dropna()
    print(f"{hosp:<10} | {len(sub):<7} | {ia_data.mean():<14.2f} | {ia_data.median():<12.2f} | {ta_data.mean():<14.2f} | {ta_data.median():<12.2f}")
print("="*80)

#1
fig, axes = plt.subplots(2, 2, figsize=(15, 9))

#2
sns.histplot(data=df.dropna(subset=['IA_min']), x='IA_min', hue='Hospital ID', element='step', stat='density', common_norm=False, ax=axes[0, 0])
axes[0, 0].set_title("Distribución de Intervalos entre Arribos (IA) por Hospital")
axes[0, 0].set_xlabel("Minutos")

#3
sns.boxplot(data=df, x='Hospital ID', y='IA_min', ax=axes[0, 1])
axes[0, 1].set_title("Dispersión y Outliers de IA por Hospital")

#4
sns.histplot(data=df, x='TA_min', hue='Hospital ID', element='step', stat='density', common_norm=False, ax=axes[1, 0])
axes[1, 0].set_title("Distribución del Tiempo de Atención Médica (TA) por Hospital")
axes[1, 0].set_xlabel("Minutos")

#5
sns.boxplot(data=df, x='Hospital ID', y='TA_min', ax=axes[1, 1])
axes[1, 1].set_title("Dispersión de TA por Hospital")

plt.tight_layout()
plt.show()

"""#5. AJUSTE DE FUNCIONES DE DENSIDAD DE PROBABILIDAD (FDP)"""

df_hosp = df[df['Hospital ID'] == 'HOSP-2'].copy()
datos_ia = df_hosp['IA_min'].dropna().values
datos_ta = df_hosp['TA_min'].dropna().values

DISTRIBUCIONES = ['expon', 'gamma', 'lognorm', 'weibull_min']

def evaluar_ajustes(datos, nombre_variable):
    print(f"\n--- Evaluando ajustes para: {nombre_variable} ---")
    filas = []
    for d_name in DISTRIBUCIONES:
        dist = getattr(stats, d_name)
        params = dist.fit(datos)

        ks_res = stats.kstest(datos, d_name, args=params)

        log_lik = np.sum(dist.logpdf(datos, *params))
        k = len(params)
        n = len(datos)
        aic = 2 * k - 2 * log_lik
        bic = k * np.log(n) - 2 * log_lik

        filas.append({
            'Distribución': d_name,
            'KS Stat (D)': round(ks_res.statistic, 4),
            'p-value': round(ks_res.pvalue, 4),
            'AIC': round(aic, 1),
            'BIC': round(bic, 1),
            'Parámetros': params
        })
    df_eval = pd.DataFrame(filas).sort_values('KS Stat (D)').reset_index(drop=True)
    return df_eval

eval_ia = evaluar_ajustes(datos_ia, "Intervalo entre Arribos (IA)")
print(eval_ia[['Distribución', 'KS Stat (D)', 'p-value', 'AIC', 'BIC']])

eval_ta = evaluar_ajustes(datos_ta, "Tiempo de Atención Médica (TA)")
print(eval_ta[['Distribución', 'KS Stat (D)', 'p-value', 'AIC', 'BIC']])

print(df['IA_global_min'].describe())

loc_g, scale_g = stats.expon.fit(df['IA_global_min'].dropna())
lambda_g = 1 / scale_g
print(f"IA_global -> lambda={lambda_g:.6f} pac/min | media entre arribos={scale_g:.2f} min")

rho_1medico = datos_ta.mean() / scale_g
print(f"rho con 1 médico: {rho_1medico:.3f}")

df_hosp2 = df[df['Hospital ID'] == 'HOSP-2'].copy()


print(df_hosp2.groupby('Urgency Level')['TA_min'].describe())

sns.boxplot(data=df_hosp2, x='Urgency Level', y='TA_min', order=['Low', 'Medium', 'High', 'Critical'])
plt.title("TA por nivel de urgencia - HOSP-2")
plt.show()

from scipy.stats import kruskal
grupos = [g['TA_min'].values for _, g in df_hosp2.groupby('Urgency Level')]
stat, p = kruskal(*grupos)
print(f"Kruskal-Wallis: H={stat:.3f}, p-valor={p:.4f}")

"""#6. GENERACIÓN DE VARIABLES ALEATORIAS POR TRANSFORMADA INVERSA"""

loc_ia, scale_ia = eval_ia.loc[eval_ia['Distribución'] == 'expon', 'Parámetros'].values[0]
lambda_ia = 1.0 / scale_ia

params_ta = eval_ta.loc[eval_ta['Distribución'] == 'gamma', 'Parámetros'].values[0]
a_ta, loc_ta, scale_ta = params_ta

N_SIM = 2000
np.random.seed(42)

tau_ia = np.random.uniform(0, 1, size=N_SIM)
tau_ta = np.random.uniform(0, 1, size=N_SIM)

ia_simulado = loc_ia - (1.0 / lambda_ia) * np.log(1.0 - tau_ia)

ta_simulado = stats.gamma.ppf(tau_ta, a=a_ta, loc=loc_ta, scale=scale_ta)

print("Variables simuladas con éxito.")
print(f"IA Real -> Media: {datos_ia.mean():.2f} min | IA Simulado -> Media: {ia_simulado.mean():.2f} min")
print(f"TA Real -> Media: {datos_ta.mean():.2f} min | TA Simulado -> Media: {ta_simulado.mean():.2f} min")

"""# 7. VERIFICACIÓN GRÁFICA Y CORRELACIÓN DE MUESTRAS"""

fig, axes = plt.subplots(1, 2, figsize=(16, 5))

axes[0].hist(datos_ia, bins=35, density=True, alpha=0.5, color='royalblue', label='Datos Reales (Empíricos)')
axes[0].hist(ia_simulado, bins=35, density=True, alpha=0.4, color='orange', label='Datos Simulados (Inv. Transform)')
x_ia = np.linspace(0, np.percentile(datos_ia, 98), 200)
axes[0].plot(x_ia, stats.expon.pdf(x_ia, loc=loc_ia, scale=scale_ia), 'r-', lw=2.5, label='FDP Teórica (Exponencial)')
axes[0].set_title("Verificación de Arribos (IA): Real vs Simulado")
axes[0].set_xlabel("Minutos")
axes[0].set_ylabel("Densidad de Probabilidad")
axes[0].legend()
axes[1].hist(datos_ta, bins=35, density=True, alpha=0.5, color='seagreen', label='Datos Reales (Empíricos)')
axes[1].hist(ta_simulado, bins=35, density=True, alpha=0.4, color='gold', label='Datos Simulados (Inv. Transform)')
x_ta = np.linspace(0, np.percentile(datos_ta, 98), 200)
axes[1].plot(x_ta, stats.gamma.pdf(x_ta, a=a_ta, loc=loc_ta, scale=scale_ta), 'r-', lw=2.5, label='FDP Teórica (Gamma)')
axes[1].set_title("Verificación de Atención (TA): Real vs Simulado")
axes[1].set_xlabel("Minutos")
axes[1].set_ylabel("Densidad de Probabilidad")
axes[1].legend()

plt.tight_layout()
plt.show()

"""# 8. PARÁMETROS OBTENIDOS LISTOS(TEI / TEF)"""

print("\n" + "="*75)
print("PARÁMETROS OBTENIDOS PARA IMPLEMENTAR EN LA SIMULACIÓN:")
print("="*75)
print(f"1. EVENTO LLEGADA DE PACIENTE (IA):")
print(f"   - Distribución: Exponencial")
print(f"   - Tasa de arribos (lambda): {lambda_ia:.6f} pacientes/minuto")
print(f"   - Tiempo medio entre arribos (1/lambda): {scale_ia:.2f} minutos ({scale_ia/60:.2f} horas)")
print(f"   - Ecuación TEF: Reloj_Llegada = Reloj + (-{scale_ia:.2f} * ln(1 - RND))")
print(f"\n2. EVENTO FIN DE ATENCIÓN MÉDICA (TA):")
print(f"   - Distribución: Gamma")
print(f"   - Parámetros: forma (a)={a_ta:.4f}, loc={loc_ta:.4f}, escala={scale_ta:.4f}")
print(f"   - Tiempo medio de atención: {datos_ta.mean():.2f} minutos")
print(f"   - Ecuación TEF: Reloj_Fin_Atencion = Reloj + stats.gamma.ppf(RND, a={a_ta:.4f}, loc={loc_ta:.4f}, scale={scale_ta:.4f})")
print("="*75)

"""# Conclusiones y Apreciaciones del Trabajo:

A partir del análisis exploratorio sobre un lote de 5.000 registros hospitalarios, se caracterizó el comportamiento estocástico de las variables críticas de una guardia médica. La segmentación cronológica individual demostró que los 5 centros asistenciales operan bajo regímenes análogos de demanda y tiempos de atención.  

Respecto al Intervalo entre Arribos ($IA$). Si bien la distribución Gamma arrojó métricas similares, su parámetro de forma $a \approx 0.98$ confirmó su degeneración en una Exponencial pura. Este resultado valida la hipótesis fundamental de la teoría de colas: las llegadas de pacientes configuran un Proceso de Poisson homogéneo con tasa media $\lambda = 0.001952\text{ pacientes/minuto}$.  En cuanto al Tiempo de Atención Médica ($TA$), se concluyó que la variable no presenta carencia de memoria y responde a una función de densidad Gamma ($a = 1.4594$, $\text{loc} = 1.9437$, $\text{escala} = 29.7626$), la cual captura la asimetría positiva propia de procedimientos clínicos con duración promedio de $45.38$ minutos.
La posterior generación de variables aleatorias mediante el Método de la Transformada Inversa comprobó la convergencia entre los datos simulados y los datos reales observados, registrando errores relativos inferiores al $1.5\%$ en ambos momentos centrales.  

La realización de este trabajo práctico nos permitió comprender de manera práctica la transición entre el análisis descriptivo de datos empíricos y la formulación analítica requerida para la ingeniería de simulación. Identificamos la importancia de no seleccionar modelos probabilísticos de forma automática mediante algoritmos de ajuste ciego, sino de contrastar la evidencia matemática con la naturaleza física del sistema real analizado.
"""